# Welcome to Lab: Simpson's Paradox 🔬

Before this lab section, you learned about Simpson's Paradox and confounding variables in lecture.  This week, you will find Simpson's Paradox through analysis of a dataset in Python, and get some practice writing conditionals for pandas DataFrames! 

A few tips to remember:

- Refer to your **lecture notebook** and the **pandas cheat sheet** to help you out with the code!
- If you find yourself stuck for more than a few minutes, ask a neighbor or course staff for help!  When you are giving help to your neighbor, explain the **idea and approach** to the problem without sharing the answer itself so they can have the same **<i>ah-hah</i>** moment!
- We are here to help you!  Don't feel embarrassed or shy to ask us for help!

Let's get started!

In [ ]:
# Meet your CAs and TA if you haven't already!
# ...first name is enough, we'll know who they are! :)
ta_name = "Tianyi"
ca1_name = "Jerry"
ca2_name = "Vikram"


# Say hello to each other!
# - Groups of 3 are ideal :)
# - However, groups of 2 or 4 are fine too!
#
# QOTD to Ask Your Group: "Orange or Blue?"
partner1_name = "Charlotte"
partner1_netid = "cs112"
partner1_orange_or_blue = "orange"

partner2_name = ""
partner2_netid = ""
partner2_orange_or_blue = ""

partner3_name = ""
partner3_netid = ""
partner3_orange_or_blue = ""

<hr style="color: #DD3403;">

# Part 1: The GPA Dataset

Many of you have likely come across one of the GPA visualizations found at https://waf.cs.illinois.edu/discovery/gpa/, potentially out of 
curiosity or the need to investigate a mysterious GenEd class you signed up for. 

Regardless, these visualizations are built on the **GPA Dataset** of UIUC students across all course subjects. Today, you're going to do some analysis and discover a case of Simpson's Paradox within data taken from UIUC courses!

## Load the GPA Dataset

The most recent version of the "GPA Dataset" is available here:
```
https://raw.githubusercontent.com/wadefagen/datasets/master/gpa/uiuc-gpa-dataset.csv
```

Use Python to load this dataset into a DataFrame called `df`:

In [3]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/wadefagen/datasets/master/gpa/uiuc-gpa-dataset.csv")
df

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,B-,C+,C,C-,D+,D,D-,F,W,Primary Instructor
0,2021,Fall,2021-fa,AAS,100,Intro Asian American Studies,DIS,2,14,2,...,3,0,1,0,0,0,0,0,0,"Zheng, Reanne"
1,2021,Fall,2021-fa,AAS,100,Intro Asian American Studies,DIS,0,15,0,...,1,0,2,0,0,0,0,1,0,"Atienza, Paul Michael L"
2,2021,Fall,2021-fa,AAS,100,Intro Asian American Studies,OD,7,4,1,...,0,2,3,0,0,1,0,1,0,"Wang, Yu"
3,2021,Fall,2021-fa,AAS,100,Intro Asian American Studies,DIS,1,18,0,...,1,0,0,0,0,0,0,0,0,"Zheng, Reanne"
4,2021,Fall,2021-fa,AAS,100,Intro Asian American Studies,DIS,0,16,1,...,1,0,2,0,0,0,0,0,0,"Atienza, Paul Michael L"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61552,2010,Summer,2010-su,STAT,410,Statistics and Probability II,LEC,5,10,2,...,1,0,1,3,0,0,0,2,1,"Stepanov, Alexei G"
61553,2010,Summer,2010-su,STAT,440,Statistical Data Management,LEC,4,12,8,...,0,0,0,0,0,0,0,0,0,"Unger, David"
61554,2010,Summer,2010-su,TAM,212,Introductory Dynamics,LEC,0,1,3,...,7,5,1,1,0,2,0,1,0,"Morgan, William T"
61555,2010,Summer,2010-su,TAM,251,Introductory Solid Mechanics,LCD,1,2,2,...,0,3,3,2,0,0,1,1,0,"Ott-Monsivais, Stephanie"
61556,2010,Summer,2010-su,TAM,335,Introductory Fluid Mechanics,LEC,5,8,9,...,1,0,4,0,0,1,0,2,0,"Keane, Richard D"

### 🔬 Test Case Checkpoint 🔬

In [2]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert(len(df) == 61557 ), "This is not the GPA dataset you're looking for"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

## Data Cleaning

The GPA dataset contains only raw GPA data and is not the easiest to work with if we want to analyze intricacies such as the average GPA or passing rate.  Luckily, DataFrames are modifiable, so we can add more columns based on what questions we want to answer.

The process of modifying a dataset via deletion (cleaning up empty/unwanted values) or addition (adding new columns) is often called **data cleaning**. This is an important concept in Data Science, because you won't always receive your data in the perfect format for your purposes.

With the GPA dataset, we want to investigate one innocent question posed by a theoretical incoming student: 
- *Is it easier to get an A in STAT or CS courses at UIUC?*

To do this, we'll need to first perform some modifications on our loaded DataFrame, `df`. Specifically, we will need to create two new columns:
- A `Total` column,  the total number of students in every course
- An `A_Grade` column, the total number of students receiving an A+, A, or A- in every course

### Puzzle 1.1: Creating a `Total Students` Column

Create the new column `Total Students` that stores the total number of students in every course.

- The `Total Students` column should include every grade **except** `W`.  W means the student withdrew from the course. We don't want to include withdraws in our analysis.

In [8]:
df['Total Students'] = df['A+'] + df['A'] + df['A-'] + df['B+'] + df['B'] + df['B-'] + df['C+'] + df['C'] + df['C-'] + df['D+'] + df['D'] + df['D-'] + df['F']
df

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C+,C,C-,D+,D,D-,F,W,Primary Instructor,Total Students
0,2021,Fall,2021-fa,AAS,100,Intro Asian American Studies,DIS,2,14,2,...,0,1,0,0,0,0,0,0,"Zheng, Reanne",30
1,2021,Fall,2021-fa,AAS,100,Intro Asian American Studies,DIS,0,15,0,...,0,2,0,0,0,0,1,0,"Atienza, Paul Michael L",27
2,2021,Fall,2021-fa,AAS,100,Intro Asian American Studies,OD,7,4,1,...,2,3,0,0,1,0,1,0,"Wang, Yu",27
3,2021,Fall,2021-fa,AAS,100,Intro Asian American Studies,DIS,1,18,0,...,0,0,0,0,0,0,0,0,"Zheng, Reanne",26
4,2021,Fall,2021-fa,AAS,100,Intro Asian American Studies,DIS,0,16,1,...,0,2,0,0,0,0,0,0,"Atienza, Paul Michael L",28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61552,2010,Summer,2010-su,STAT,410,Statistics and Probability II,LEC,5,10,2,...,0,1,3,0,0,0,2,1,"Stepanov, Alexei G",31
61553,2010,Summer,2010-su,STAT,440,Statistical Data Management,LEC,4,12,8,...,0,0,0,0,0,0,0,0,"Unger, David",28
61554,2010,Summer,2010-su,TAM,212,Introductory Dynamics,LEC,0,1,3,...,5,1,1,0,2,0,1,0,"Morgan, William T",28
61555,2010,Summer,2010-su,TAM,251,Introductory Solid Mechanics,LCD,1,2,2,...,3,3,2,0,0,1,1,0,"Ott-Monsivais, Stephanie",21
61556,2010,Summer,2010-su,TAM,335,Introductory Fluid Mechanics,LEC,5,8,9,...,0,4,0,0,1,0,2,0,"Keane, Richard D",39

**Note:** Our DataFrame is so large that you may have to scroll to the right to see the new column, `Total Students`.

### Puzzle 1.2: Creating an `A_Grade` Column

Create the new column `A_Grade` that stores the total number of "A"s given in every course.

- We consider an "A" to be any type of A, in other words "A+", "A", or an "A-" are all included.

In [9]:
df['A_Grade'] = df['A+'] + df['A'] + df['A-']

### 🔬 Test Case Checkpoint 🔬

In [10]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert('A_Grade' in df), "Make sure you've named the A_Grade column properly and added it to the dataframe"
assert(df['A_Grade'].sum() == 1983288), "Double check the values of your A_Grade column, and make sure you are calling .sum() on the correct list (A_Grade)"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

# Part 2: Working with the GPA Dataset
Now that we have our columns set up, we can perform basic mathematical analysis on the DataFrame to get insight towards our question. 

Should be simple, right? Let's just see which subject, STAT or CS, has a greater percentage of A grades .

### Puzzle 2.1: Subject DataFrames

Select only the rows of the GPA dataset `df` with a `Subject` of `STAT`. Assign these rows to a new DataFrame, `df_STAT`. 
- Make sure your result only contains STAT courses!

In [17]:
df_STAT = df[df["Subject"] == "STAT"]

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C,C-,D+,D,D-,F,W,Primary Instructor,Total Students,A_Grade
2576,2021,Fall,2021-fa,STAT,100,Statistics,LCD,150,78,49,...,18,10,5,5,3,18,3,"Flanagan, Karle A",442,277
2577,2021,Fall,2021-fa,STAT,100,Statistics,ONL,208,151,81,...,42,24,17,25,5,45,9,"Flanagan, Karle A",836,440
2578,2021,Fall,2021-fa,STAT,107,Data Science Discovery,OLC,127,61,33,...,5,4,2,2,0,12,2,"Flanagan, Karle A",287,221
2579,2021,Fall,2021-fa,STAT,200,Statistical Analysis,ONL,75,135,34,...,9,3,0,0,1,3,0,"Fireman, Ellen S",322,244
2580,2021,Fall,2021-fa,STAT,207,Data Science Exploration,LEC,17,3,2,...,1,0,0,0,1,3,1,"Ellison, Victoria M",29,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61549,2010,Summer,2010-su,STAT,100,Statistics,LCD,1,13,3,...,2,2,3,1,1,1,0,"Hirtz, Nathaniel R",39,17
61550,2010,Summer,2010-su,STAT,100,Statistics,LCD,0,14,3,...,3,0,0,1,0,3,1,"Dalpiaz, David M",28,17
61551,2010,Summer,2010-su,STAT,400,Statistics and Probability I,LEC,4,15,7,...,2,2,0,1,0,3,1,"Monrad, Ditlev",47,26
61552,2010,Summer,2010-su,STAT,410,Statistics and Probability II,LEC,5,10,2,...,1,3,0,0,0,2,1,"Stepanov, Alexei G",31,17
61553,2010,Summer,2010-su,STAT,440,Statistical Data Management,LEC,4,12,8,...,0,0,0,0,0,0,0,"Unger, David",28,24

Select only the rows of the GPA dataset `df` with a `Subject` of `CS`. Assign these rows to a new dataframe, `df_CS`. 
- Make sure your result only contains CS courses!

In [12]:
df_CS = df[df["Subject"] == "CS"]

### 🔬 Test Case Checkpoint 🔬

In [13]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.
assert( 'df_STAT' in vars() ), "Make certain to name the STAT courses df_STAT."
assert( 'df_CS' in vars() ), "Make certain to name the CS courses df_CS."
assert( len(df_STAT[df_STAT.Subject != "STAT"] ) == 0 ), "It looks like you did not subset df_STAT to only STAT courses."
assert( len(df_CS[df_CS.Subject != "CS"] ) == 0 ), "It looks like you did not subset df_STAT to only STAT courses."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Puzzle 2.2: Comparing Overall Percentages

With our two new dataframes of STAT and CS courses, use the following code cell to determine the **percentage** of A grades recieved in STAT and CS courses, storing them as variables `stat_a` and `cs_a` respectively. 

Print statements have been provided to show the values you calculate. 

**Hint:** To find the % of As, divide the total number of students by the total number of As. Remember the function `sum(df['column_name'])` can be used to add up the values of all rows in a particular column of a dataframe.

In [26]:
stat_a = sum(df_STAT["A_Grade"]) / sum(df_STAT["Total Students"])
print(f'Overall % of As in STAT is: {stat_a}')

cs_a = sum(df_CS["A_Grade"]) / sum(df_CS["Total Students"])
print(f'Overall % of As in CS is: {cs_a}')

Overall % of As in STAT is: 0.6027997446909787
Overall % of As in CS is: 0.5891362965182221

### 🔬 Test Case Checkpoint 🔬

In [27]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
import math
assert(math.isclose(stat_a, 0.6027997446909787)), "The overall percentage of A grades recieved in STAT courses does not appear to have been correctly calculated"
assert(math.isclose(cs_a, 0.5891362965182221)), "The overall percentage of A grades recieved in CS courses does not appear to have been correctly calculated"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Analysis: Good Comparison?
**Q: What conclusion can you take from the overall percentages found above when asking the original question:**
- *Is it easier to get an A in STAT or CS courses at UIUC?*

Stats

**Q: Given what you've learned about experimental design, what are some reasons (specific to this dataset) you may not trust this conclusion? If you would trust it, explain why.**

There may exists confounding variables due to the different courses.

## An Extra Consideration

If you look at the `Year` column of our GPA dataset, you might notice that we have some old data in our set - all the way back to **2010**! This means we aren't really answering our question from the perspective of a student now. 

If we want to know if it is easier to **currently** get an A in a STAT or CS course, we should control for the **date** of the data by looking at more **recent years** specifically.

### Puzzle 2.3: More DataFrames

Using the code cells below, define four new DataFrames by selecting from rows of our previously created `df_CS` and `df_STAT`. 

- `df_cs_recent`: all `CS` course data in *recent years*
- `df_stat_recent`: all `STAT` course data in *recent years*
- `df_cs_old`: all other, older `CS` course data
- `df_stat_old`: all other, older `STAT` course data

Define *recent years* as **any year after and including 2020**, and older years as any year before 2020. 

Feel free to use row selection conditionals OR the `.isin()` function you learned in the last lab.

In [30]:
df_stat_recent = df_STAT[df_STAT.Year >= 2020]
df_stat_recent

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C,C-,D+,D,D-,F,W,Primary Instructor,Total Students,A_Grade
2576,2021,Fall,2021-fa,STAT,100,Statistics,LCD,150,78,49,...,18,10,5,5,3,18,3,"Flanagan, Karle A",442,277
2577,2021,Fall,2021-fa,STAT,100,Statistics,ONL,208,151,81,...,42,24,17,25,5,45,9,"Flanagan, Karle A",836,440
2578,2021,Fall,2021-fa,STAT,107,Data Science Discovery,OLC,127,61,33,...,5,4,2,2,0,12,2,"Flanagan, Karle A",287,221
2579,2021,Fall,2021-fa,STAT,200,Statistical Analysis,ONL,75,135,34,...,9,3,0,0,1,3,0,"Fireman, Ellen S",322,244
2580,2021,Fall,2021-fa,STAT,207,Data Science Exploration,LEC,17,3,2,...,1,0,0,0,1,3,1,"Ellison, Victoria M",29,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9936,2020,Winter,2020-wi,STAT,420,Statistical Modeling in R,ONL,28,123,18,...,1,0,0,0,0,1,0,"Unger, David",185,169
9937,2020,Winter,2020-wi,STAT,420,Methods of Applied Statistics,ONL,5,14,5,...,0,0,0,0,0,1,0,"Unger, David",25,24
9938,2020,Winter,2020-wi,STAT,420,Methods of Applied Statistics,ONL,10,48,11,...,1,0,0,0,0,2,1,"Unger, David",86,69
9939,2020,Winter,2020-wi,STAT,440,Statistical Data Management,ONL,0,29,0,...,0,0,0,0,0,3,1,"Kinson, Christopher L",36,29
9940,2020,Winter,2020-wi,STAT,448,Advanced Data Analysis,ONL,5,8,0,...,1,0,0,0,0,1,0,"Bravo De Guenni, Lelys",21,13

In [33]:
df_cs_recent = df_CS[df_CS.Year >= 2020]
df_cs_recent

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C,C-,D+,D,D-,F,W,Primary Instructor,Total Students,A_Grade
800,2021,Fall,2021-fa,CS,100,Freshman Orientation,LEC,0,246,7,...,0,0,0,0,0,2,0,"Gunter, Elsa",261,253
801,2021,Fall,2021-fa,CS,100,Freshman Orientation,OLC,0,223,6,...,1,0,0,2,0,6,2,"Gunter, Elsa",241,229
802,2021,Fall,2021-fa,CS,101,Intro Computing: Engrg & Sci,OLC,112,264,48,...,7,5,4,2,2,10,2,"Davis, Neal E",520,424
803,2021,Fall,2021-fa,CS,105,Intro Computing: Non-Tech,OLC,27,83,53,...,20,11,9,6,1,24,9,"Zilles, Craig",348,163
804,2021,Fall,2021-fa,CS,105,Intro Computing: Non-Tech,OLC,23,100,37,...,19,9,6,5,4,14,6,"Zilles, Craig",342,160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9785,2020,Winter,2020-wi,CS,498,Data Visualiztion,ONL,226,169,30,...,3,0,3,0,0,9,0,"Hart, John C",476,425
9786,2020,Winter,2020-wi,CS,498,Data Visualiztion,OLC,20,14,3,...,0,0,0,0,0,1,2,"Hart, John C",46,37
9787,2020,Winter,2020-wi,CS,513,Theory & Pract Data Cleaning,ONL,350,28,3,...,0,0,0,0,0,1,0,"Ludaescher, Bertram",390,381
9788,2020,Winter,2020-wi,CS,598,Cloud Capstone,ONL,35,6,0,...,0,0,0,0,0,1,0,"Farivar, Reza",43,41
9789,2020,Winter,2020-wi,CS,598,Data Mining Capstone,ONL,28,19,2,...,1,0,0,0,0,0,0,"Farivar, Reza",57,49

In [34]:
df_stat_old = df_STAT[df_STAT.Year < 2020]
df_stat_old

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C,C-,D+,D,D-,F,W,Primary Instructor,Total Students,A_Grade
12452,2019,Fall,2019-fa,STAT,100,Statistics,ONL,69,105,63,...,25,12,4,10,1,13,2,"Flanagan, Karle A",477,237
12453,2019,Fall,2019-fa,STAT,100,Statistics,LCD,71,143,95,...,24,19,19,14,5,8,4,"Flanagan, Karle A",589,309
12454,2019,Fall,2019-fa,STAT,100,Statistics,ONL,19,72,23,...,19,3,5,4,3,9,1,"Yu, Albert",254,114
12455,2019,Fall,2019-fa,STAT,107,Data Science Discovery,LEC,6,109,7,...,3,3,4,2,0,5,2,"Flanagan, Karle A",170,122
12456,2019,Fall,2019-fa,STAT,200,Statistical Analysis,LCD,28,1,1,...,0,1,0,0,0,1,0,"Simpson, Douglas G",39,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61549,2010,Summer,2010-su,STAT,100,Statistics,LCD,1,13,3,...,2,2,3,1,1,1,0,"Hirtz, Nathaniel R",39,17
61550,2010,Summer,2010-su,STAT,100,Statistics,LCD,0,14,3,...,3,0,0,1,0,3,1,"Dalpiaz, David M",28,17
61551,2010,Summer,2010-su,STAT,400,Statistics and Probability I,LEC,4,15,7,...,2,2,0,1,0,3,1,"Monrad, Ditlev",47,26
61552,2010,Summer,2010-su,STAT,410,Statistics and Probability II,LEC,5,10,2,...,1,3,0,0,0,2,1,"Stepanov, Alexei G",31,17
61553,2010,Summer,2010-su,STAT,440,Statistical Data Management,LEC,4,12,8,...,0,0,0,0,0,0,0,"Unger, David",28,24

In [36]:
df_cs_old = df_CS[df_CS.Year < 2020]
df_cs_old

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C,C-,D+,D,D-,F,W,Primary Instructor,Total Students,A_Grade
10833,2019,Fall,2019-fa,CS,100,Freshman Orientation,LEC,0,214,22,...,12,10,4,2,2,4,0,"Gunter, Elsa",341,236
10834,2019,Fall,2019-fa,CS,101,Intro Computing: Engrg & Sci,LEC,282,135,62,...,6,3,4,3,5,12,0,"Davis, Neal E",610,479
10835,2019,Fall,2019-fa,CS,105,Intro Computing: Non-Tech,LEC,86,134,87,...,37,14,12,10,10,14,4,"Harris, Albert F",601,307
10836,2019,Fall,2019-fa,CS,125,Intro to Computer Science,LEC,150,357,45,...,11,6,0,13,0,23,3,"Challen, Geoffrey W",671,552
10837,2019,Fall,2019-fa,CS,126,Software Design Studio,LCD,9,56,37,...,3,1,3,0,2,3,2,"Woodley, Michael J",145,102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61433,2010,Summer,2010-su,CS,101,Intro Computing: Engrg & Sci,LBD,4,6,2,...,0,1,0,0,0,0,0,"Gambill, Thomas N",21,12
61434,2010,Summer,2010-su,CS,225,Data Structures,LBD,1,5,1,...,3,1,0,2,0,1,0,"Earls, John C",21,7
61435,2010,Summer,2010-su,CS,373,Theory of Computation,LEC,5,1,5,...,0,2,0,2,0,1,1,"Kumar, Viraj",26,11
61436,2010,Summer,2010-su,CS,421,Progrmg Languages & Compilers,LCD,2,5,5,...,1,4,0,4,0,0,1,"Hafiz, Munawar",30,12
61437,2010,Summer,2010-su,CS,598,Object-Oriented Prog & Design,ONL,3,22,0,...,0,0,0,0,0,0,0,"Johnson, Ralph E",30,25

### 🔬 Test Case Checkpoint 🔬

In [37]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any error our output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cell, make changes, and RE-RUN your code and then this cell.
assert( 'df_stat_recent' in vars() ), "Make certain to name the recent STAT courses df_stat_recent."
assert( 'df_cs_recent' in vars() ), "Make certain to name the recent CS courses df_cs_recent."
assert( 'df_stat_old' in vars() ), "Make certain to name the old STAT courses df_stat_old."
assert( 'df_cs_old' in vars() ), "Make certain to name the old CS courses df_cs_old."

assert( len(df_stat_recent[df_stat_recent.Year < 2020] ) == 0 ), "Make sure only years after and including 2020 are in the df_stat_recent dataframe."
assert( len(df_cs_recent[df_cs_recent.Year < 2020] ) == 0 ), "Make sure only years after and including 2020 are in the df_cs_recent dataframe."
assert( len(df_stat_old[df_stat_old.Year >= 2020] ) == 0 ), "Make sure only years before 2020 are in the df_stat_old dataframe."
assert( len(df_cs_old[df_cs_old.Year >= 2020] ) == 0 ), "Make sure only years before 2020 are in the df_cs_old dataframe."

assert(len(df[ df.index.isin(df_stat_recent.index) & df.index.isin(df_stat_old.index) ]) == 0), "Check for duplicate values in your df_stat_recent and df_stat_old dataframes."
assert(len(df[ df.index.isin(df_cs_recent.index) & df.index.isin(df_cs_old.index) ]) == 0), "Check for duplicate values in your df_cs_recent and df_cs_old dataframes."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Puzzle 2.4: New Analysis
Now that we've got all the DataFrames setup with GPA data of the CS and STAT courses separated by recency (2020 or newer being 'recent'), we can do more in-depth analysis to investigate our question. 

In the following code cells, **calculate the percentages** described by the comment. Your answer should be a decimal between 0 and 1. 

**Hint:** the function `sum(df['column_name'])` can be used to add up the values of all rows in a particular column of a DataFrame.

In [38]:
# Percentage of As received in CS in recent years
cs_recent_a = sum(df_cs_recent["A_Grade"]) / sum(df_cs_recent["Total Students"])
print(f'Percentage of As received in CS in recent years: {cs_recent_a}')

Percentage of As received in CS in recent years: 0.7305164527732138

In [39]:
# Percentage of As received in STAT in recent years
stat_recent_a = sum(df_stat_recent["A_Grade"]) / sum(df_stat_recent["Total Students"])
print(f'Percentage of As received in STAT in recent years: {stat_recent_a}')

Percentage of As received in STAT in recent years: 0.683119837776349

In [40]:
# percentage of As recieved in CS in older years
cs_old_a = sum(df_cs_old["A_Grade"]) / sum(df_cs_old["Total Students"])
print(f'Percentage of As received in CS in older years: {cs_old_a}')

Percentage of As received in CS in older years: 0.5442563329057359

In [41]:
# percentage of As recieved in CS in older years
stat_old_a = sum(df_stat_old["A_Grade"]) / sum(df_stat_old["Total Students"])
print(f'Percentage of As received in STAT in older years: {stat_old_a}')

Percentage of As received in STAT in older years: 0.5803123874934227

### 🔬 Test Case Checkpoint 🔬

In [42]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert(math.isclose(cs_recent_a,  0.7305164527732138)), "The overall percentage of A grades recieved in STAT courses recently does not appear to have been correctly calculated"
assert(math.isclose(stat_recent_a, 0.683119837776349)), "The overall percentage of A grades recieved in CS courses recently does not appear to have been correctly calculated"

assert(math.isclose(cs_old_a,  0.5442563329057359)), "The overall percentage of A grades recieved in STAT courses in older years does not appear to have been correctly calculated"
assert(math.isclose(stat_old_a, 0.5803123874934227)), "The overall percentage of A grades recieved in CS courses in older years does not appear to have been correctly calculated"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Observe the Results
Run the following cell to format all of your answers as a DataFrame, keeping in mind that "Old" means data from courses before 2020, and "New" means courses held during or after 2020.

In [43]:
pd.DataFrame([
  {'Old % of A': cs_old_a, 'New % of A': cs_recent_a, 'Overall % of A': cs_a},
  {'Old % of A': stat_old_a, 'New % of A': stat_recent_a, 'Overall % of A': stat_a}
], index=['CS', 'STAT'])

      Old % of A  New % of A  Overall % of A
CS      0.544256    0.730516        0.589136
STAT    0.580312    0.683120        0.602800

Notice that when observing the overall % of A grades received, you may think `STAT` is easier than `CS` to get an A in. But in the sub-group of the courses held in years of 2020 and later, we see that CS actually has a higher A-Grade rate! 

This is **Simpson's Paradox**: a pattern within a population can appear, disappear, or reverse when you look at subpopulations.

In more formal terms, Simpson's Paradox can cause you to observe a pattern reverse when you look at the overall group statistics versus statistics of groups post-stratification. In this case we are stratifying by time.

### Analysis: Reflecting on New Observations

You should see the pattern reverse when you look at the overall A grade percentages vs. the percentages stratified to account for recency. This is called **Simpson's Paradox**: a pattern within a population can appear, disappear, or reverse when you look at subpopulations.

Now think about how would you now respond differently to the incoming student's question:
- *Is it easier to get an A in STAT or CS courses at UIUC?*

**Q: Which comparison of percentages do you trust more and why? Are there any other potential confounding variables when answering this question that could be investigated further? Respond with at least three full sentences.**

I trust more about the stratification ones.  Other confounding variables may be the course level. CS may have more students in upper-level classes while Stats may have more studnets in lower-level classes.

<hr style="color: #DD3403;">

# Part 3: Revisiting the Hello Dataset

Over the past two weeks, you created a series of questions that made up the "Hello Dataset" and completed the survey by answering all of the questions yourself. Now, we will load this dataset again and briefly answer a few questions.

## Load the Hello Dataset

The "Hello Dataset" is available here:
```
https://waf.cs.illinois.edu/discovery/hello-fa22.csv
```

Use Python to load this dataset into a DataFrame called `df_hello`:

In [47]:
import pandas as pd
df_hello = pd.read_csv("https://waf.cs.illinois.edu/discovery/hello-fa22.csv")
df_hello

,Name,Lab,Number 1 or Number 2?,Number 3 or Number 5?,What is your preferred way of saying one half?,7UP or Sierra Mist?,Android or iOS?,Apple or Orange?,Beef or Pork?,Your birthday is...,...,What is your favorite coffee shop drink?,What is your favorite mobile app?,What is your favorite subject?,Who is your favorite singer?,What is your favorite season?,What is your Zodiac sign?,What is your favorite video game?,What is your favorite non-video game?,What is your favorite food?,What's your favorite movie?
0,CA Ana,AL1,2.0,5.0,2-Jan,Sierra Mist,iOS,Apple,Pork,On/Before June 30,...,Cold brew,Snapchat,Math,Taylor Swift,Fall,Piceis,Minecraft,Chutes and Ladders,Yogurt,?
1,CA Ram,AYR,2.0,5.0,2-Jan,7UP,iOS,Apple,NaN,On/After July 1,...,Black coffee,Google chrome,Mathematics,TWICE,Spring,Scorpio,Player Unkown's Battleground,Basketball,Rice,The conjouring
2,CA Xin,AYO,1.0,5.0,2-Jan,Sierra Mist,iOS,Apple,Beef,On/Before June 30,...,starbucks,Starbucks,Psychology,Five Exercuse,Winter,aquarius,None,None,Eggs,Flipped
3,Lekha,AYH,2.0,2.0,0.5,7UP,iOS,Orange,Pork,On/After July 1,...,pumpkin spice latte,twitter,english (writing),lana del rey,autumn,leo,animal crossing,catan,tteokbokki,dune (2021)
4,Reni,AYD,2.0,5.0,2-Jan,7UP,iOS,Apple,Pork,On/Before June 30,...,Mocha,Instagram,Math,Mark kozelek,Winter,Aquarias,Rainbow six siege,Catan,Tacos,End of Evangelion
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
519,Bill,AYC,1.0,5.0,2-Jan,Sierra Mist,iOS,Apple,Beef,On/After July 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
520,Renault,AYR,2.0,5.0,0.5,Sierra Mist,Android,Orange,Pork,On/Before June 30,...,moca,wechat,cs,Michael Jackson,Spring,idk,WOW classic,badminton,rice,guardians of gahoole
521,Shivam Patel,AYC,1.0,3.0,0.5,7UP,iOS,Apple,NaN,On/Before June 30,...,Don’t have one,Youtube,World History,Kumar Sanu,Summer,Aquarius,FIFA 20,Chess,Pizza,Avengers Endgame
522,Colin,AYI,1.0,5.0,2-Jan,Sierra Mist,iOS,Orange,Beef,On/Before June 30,...,tea,YouTube,Math,The Weeknd,Summer,Aquarious,Rocket League,Poker,Tacos,Inception
523,Evan,AYG,2.0,3.0,2-Jan,7UP,Android,Orange,Beef,On/After July 1,...,Tea,Facebook,Probability and Measure Theory,Fredie Mercury,Winter,Libra,Uncharted,Basketball,Eggs with bacon,Interstellar

### 🔬 Test Case Checkpoint 🔬

In [46]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert(len(df_hello) == 524), "This is not the Hello dataset you're looking for. Check the URL."

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

## Classes v. Sleep

With the Hello Dataset, we are going to briefly explore two quantitative questions:
- How many hours of sleep do you get on average? 
- How many classes are you taking this semester?

### Puzzle 3.1: Observation Subsets

In this situation, let's define an average of **6 or more hours** of sleep as "good sleep" and any less to be defined as "bad sleep".

From this, create two DataFrames that contain subsets of the Hello Dataset: 
- `df_goodsleep`: including everyone who gets "good sleep" on average
- `df_badsleep`: including everyone who gets "bad sleep" on average

In [55]:
sleep = 'How many hours of sleep do you get on average?'
df_goodsleep = df_hello[df_hello[sleep] >= 6]
df_goodsleep

,Name,Lab,Number 1 or Number 2?,Number 3 or Number 5?,What is your preferred way of saying one half?,7UP or Sierra Mist?,Android or iOS?,Apple or Orange?,Beef or Pork?,Your birthday is...,...,What is your favorite coffee shop drink?,What is your favorite mobile app?,What is your favorite subject?,Who is your favorite singer?,What is your favorite season?,What is your Zodiac sign?,What is your favorite video game?,What is your favorite non-video game?,What is your favorite food?,What's your favorite movie?
0,CA Ana,AL1,2.0,5.0,2-Jan,Sierra Mist,iOS,Apple,Pork,On/Before June 30,...,Cold brew,Snapchat,Math,Taylor Swift,Fall,Piceis,Minecraft,Chutes and Ladders,Yogurt,?
2,CA Xin,AYO,1.0,5.0,2-Jan,Sierra Mist,iOS,Apple,Beef,On/Before June 30,...,starbucks,Starbucks,Psychology,Five Exercuse,Winter,aquarius,None,None,Eggs,Flipped
3,Lekha,AYH,2.0,2.0,0.5,7UP,iOS,Orange,Pork,On/After July 1,...,pumpkin spice latte,twitter,english (writing),lana del rey,autumn,leo,animal crossing,catan,tteokbokki,dune (2021)
4,Reni,AYD,2.0,5.0,2-Jan,7UP,iOS,Apple,Pork,On/Before June 30,...,Mocha,Instagram,Math,Mark kozelek,Winter,Aquarias,Rainbow six siege,Catan,Tacos,End of Evangelion
5,Linger,AYF,2.0,5.0,2-Jan,7UP,iOS,Apple,Beef,On/Before June 30,...,Starbucks,App Store,Any STEM,Don’t have one,Fall,Gemini,Minecraft,UNO,Authentic Chinese Food,Harry Potter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,Lauren,AYP,1.0,3.0,2-Jan,7UP,iOS,Apple,Beef,On/Before June 30,...,tea,instagram,english,ariana grande,summer,taurus,call of duty,flappy bird,pasta,the notebook
518,Celesta,AYS,1.0,3.0,0.5,7UP,iOS,Apple,Beef,On/After July 1,...,Frappuccino,instagram,science,bts,winter,capricorn,mario kart,genshin impact,ramen,disney rapanzel
519,Bill,AYC,1.0,5.0,2-Jan,Sierra Mist,iOS,Apple,Beef,On/After July 1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
520,Renault,AYR,2.0,5.0,0.5,Sierra Mist,Android,Orange,Pork,On/Before June 30,...,moca,wechat,cs,Michael Jackson,Spring,idk,WOW classic,badminton,rice,guardians of gahoole
522,Colin,AYI,1.0,5.0,2-Jan,Sierra Mist,iOS,Orange,Beef,On/Before June 30,...,tea,YouTube,Math,The Weeknd,Summer,Aquarious,Rocket League,Poker,Tacos,Inception

In [56]:
df_badsleep = df_hello[df_hello[sleep] < 6]
df_badsleep

,Name,Lab,Number 1 or Number 2?,Number 3 or Number 5?,What is your preferred way of saying one half?,7UP or Sierra Mist?,Android or iOS?,Apple or Orange?,Beef or Pork?,Your birthday is...,...,What is your favorite coffee shop drink?,What is your favorite mobile app?,What is your favorite subject?,Who is your favorite singer?,What is your favorite season?,What is your Zodiac sign?,What is your favorite video game?,What is your favorite non-video game?,What is your favorite food?,What's your favorite movie?
1,CA Ram,AYR,2.0,5.0,2-Jan,7UP,iOS,Apple,NaN,On/After July 1,...,Black coffee,Google chrome,Mathematics,TWICE,Spring,Scorpio,Player Unkown's Battleground,Basketball,Rice,The conjouring
8,Suvinay,AYP,1.0,5.0,2-Jan,7UP,Android,Orange,NaN,On/After July 1,...,Frappuccino,Netflix,Astronomy,Freddie Mercury,Spring,Sagitarrius,Minecraft,Chess,Basmati Rice,Interstellar
16,Claudia,AL1,2.0,3.0,2-Jan,Sierra Mist,iOS,Apple,Beef,On/After July 1,...,Ice caramel macchiato or salted caramel cream ...,Disney +,Math,Giveon,Spring,Capricorn,Smash bros,Uno,Chicken,Tangled
17,Wing,AYB,1.0,5.0,2-Jan,Sierra Mist,iOS,Apple,Beef,On/Before June 30,...,Bridgeport Coffees,iMessage,Math,IU,Winter,Aquarius,Valorant,Exploding Kittens,Lobster,Avengers End Game
20,Sakshyam,AYT,1.0,5.0,0.5,7UP,iOS,Orange,Beef,On/After July 1,...,Latte,Duolingo,Philosophy,Elvis Presley,summer,Scorpio,Call of duty,Ludo,Burger,Interstellar
85,Rachel,AYK,1.0,5.0,2-Jan,7UP,iOS,Apple,Beef,On/After July 1,...,Matcha latte,Instagram,Statistics,Enhypen,Fall,Virgo,Minecraft,Uno,Sushi,Your Name
90,Lily,AYB,1.0,5.0,2-Jan,7UP,iOS,Orange,Beef,On/Before June 30,...,Tous Les Jours,Discord,Math,Powfu,Summer,Cancer,Valorant,Chess,Pasta,Weathering with You
156,rafy,AYK,1.0,3.0,2-Jan,Sierra Mist,iOS,Orange,Pork,On/After July 1,...,cafe paradiso,tiktok,literature,n/a,fall,leo,mobile legends / league of legends,jenga,chocolate,my neighbor totoro
179,Alisha,AYC,1.0,5.0,2-Jan,7UP,iOS,Orange,Beef,On/Before June 30,...,Vanilla Cold Brew,Instagram,Biology,Harry Styles,Winter,Capricorn,Minecraft,Magic: The Gathering,Mac & Cheese,Black Panther
247,Oddie,AYR,1.0,3.0,2-Jan,Sierra Mist,Android,Orange,Pork,On/Before June 30,...,Cold Brew,Discord,Computer Science,Bruno Mars,Fall,Aquarius,League of Legends,Catan,Pho,Summer wars
249,Sneha,AYD,2.0,5.0,2-Jan,7UP,iOS,Apple,Pork,On/Before June 30,...,Hot Chocolate,Duolingo,Computer Science,Taylor Swift,Fall,Aries,Minecraft,Exploding Kittens,Pizza,Matrix
284,alex,AYO,2.0,5.0,0.5,7UP,iOS,Apple,Beef,On/Before June 30,...,Starbucks,Snapchat,NaN,Lil Baby,Summer,Cancer,Skyrim,Poker,Hamburger,Cars
286,JACKY,AYA,1.0,3.0,2-Jan,7UP,iOS,Apple,Beef,On/After July 1,...,americano,steam,CS,JB,spring,sheep,csgo,unio,Buger,the green book
315,Rohan,AYQ,2.0,3.0,2-Jan,7UP,iOS,Apple,NaN,On/Before June 30,...,green tea,snapchat,math,JID,winter,capricorn,hitman 3,uno,pizza,spider-man into the spider-verse
316,Jo,AYM,1.0,3.0,2-Jan,7UP,iOS,Apple,Beef,On/Before June 30,...,Cappucino,Pintrest,Neuroscience,Asake,Summer,Gemini,FIFA,Homescapes,Fried rice,47 Ronin
354,Vikas,AYE,1.0,3.0,2-Jan,7UP,iOS,Orange,Beef,On/Before June 30,...,caramel macchiato,instagram,Science,BTS,winter,Pisces,league of legends,cards,kbbq,Despicable Me
441,Akiko,AYN,2.0,5.0,2-Jan,Sierra Mist,iOS,Orange,Pork,On/Before June 30,...,Coffee,Instagram,Psychology,Eminem,Winter,Pisces,None,Homescapes,Sushi,Gurdian's of Galaxy
465,DAN,AYM,2.0,5.0,2-Jan,7UP,iOS,Orange,Beef,On/After July 1,...,Home,Spotify,Math,Kanye,SUMMER,CANCER,Halo,Tag,Jello,Fight Club
516,Edward,AYQ,1.0,5.0,0.5,Sierra Mist,iOS,Orange,Beef,On/After July 1,...,Philz,Xiaohongshu,Finance,Bruno Mars,summer,Sagittarius,I don't play games,I don't play games,Barbecue,Persuit of Happiness
521,Shivam Patel,AYC,1.0,3.0,0.5,7UP,iOS,Apple,NaN,On/Before June 30,...,Don’t have one,Youtube,World History,Kumar Sanu,Summer,Aquarius,FIFA 20,Chess,Pizza,Avengers Endgame
523,Evan,AYG,2.0,3.0,2-Jan,7UP,Android,Orange,Beef,On/After July 1,...,Tea,Facebook,Probability and Measure Theory,Fredie Mercury,Winter,Libra,Uncharted,Basketball,Eggs with bacon,Interstellar

### 🔬 Test Case Checkpoint 🔬

In [57]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert(len(df_goodsleep) == 503 ), "Double check your conditional used to create df_goodsleep from df_hello - remember, good sleep is response values of 6 hours or more"
assert(len(df_badsleep) == 21 ), "Double check your conditional used to create df_badsleep from df_hello - remember, bad sleep is response values of less than 6 hours"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Puzzle 3.2: Average Number of Classes by Group

Now find the **average number of classes** of each group (good sleep and bad sleep):

Hint: the `df['column name'].mean()` function returns the mean of all values in the specified column of `df`

In [67]:
classes = 'How many classes are you taking this semester?'
goodsleep_avg_classes = df_goodsleep[classes].mean()
goodsleep_avg_classes

,Number 1 or Number 2?,Number 3 or Number 5?,At what age do you think you will die?,"From 1 to 10, how happy are you right now?",How many classes are you taking this semester?,How many credit hours are you taking this semester?.1,How many classes do you have on Friday?,How many countries have you been to outside the US?,How many hours of sleep did you get last night?,How many hours of sleep do you get on average?,How many meals do you have one day?,How many pets do you have?,How many roommates do you have?,How many siblings do you have?,How many years do you plan to study at university?,What is your favorite number?
Lab,,,,,,,,,,,,,,,,
AYA,2.0,5.0,87.0,8.0,5.0,14.0,3,0.0,8.0,7.0,2.0,1,1.0,0.0,4.0,2.000000e+00
AL1,23.0,67.0,1457.0,129.5,84.0,260.0,41,95.0,122.5,128.0,47.0,13,21.0,24.0,65.0,2.250000e+02
ALI,1.0,5.0,101.0,10.0,5.0,15.0,2,20.0,8.0,7.0,2.0,0,1.0,1.0,4.0,4.000000e+00
AYA,36.0,100.0,2737.0,155.0,134.0,400.0,57,171.0,194.0,195.5,72.0,16,77.0,48.0,102.0,2.470000e+02
AYA and AYC,2.0,3.0,92.0,9.0,5.0,14.0,3,9.0,10.0,8.0,2.0,0,0.0,1.0,3.5,2.000000e+00
"AYA, AYQ",1.0,3.0,47.0,6.0,6.0,18.0,3,20.0,5.0,7.0,2.0,1,1.0,1.0,8.0,1.300000e+01
AYB,37.0,108.0,2200.0,183.5,136.0,415.0,58,168.0,203.0,193.5,70.5,14,53.0,53.0,112.0,3.380000e+02
"AYB, AYD",1.0,5.0,75.0,10.0,2.0,9.0,1,1.0,5.0,9.0,3.0,0,3.0,2.0,5.0,1.000000e+32
AYC,33.0,90.0,1760.0,140.5,118.0,350.0,47,107.0,152.5,156.0,58.0,16,40.0,25.0,89.0,1.608000e+03
"AYC, AYE",1.0,5.0,0.0,8.0,0.0,8.0,0,1.0,8.0,8.0,2.0,0,0.0,0.0,5.0,9.000000e+00
AYD,39.0,110.0,2286.0,190.0,146.0,442.0,72,148.0,220.5,205.5,73.0,13,36.0,29.0,115.0,4.230000e+02
AYD,1.0,3.0,58.0,8.0,5.0,16.0,3,2.0,7.5,8.0,2.5,0,1.0,2.0,4.0,4.100000e+01
"AYD, AYF",1.0,3.0,70.0,6.0,5.0,16.0,1,1.0,9.0,7.0,2.0,0,1.0,1.0,4.0,6.900000e+01
AYE,29.0,83.0,1851.0,151.0,109.0,350.0,59,138.0,151.5,148.5,58.0,12,34.0,33.0,87.0,2.740000e+02
"AYE, AYG",1.0,5.0,90.0,9.0,5.0,15.0,2,2.0,8.0,8.0,3.0,4,1.0,2.0,4.0,7.000000e+00
"AYE,AYG",2.0,3.0,90.0,8.0,4.0,16.0,3,3.0,8.0,8.0,2.0,0,0.0,0.0,4.0,0.000000e+00
AYF,35.0,103.0,2089.0,161.0,141.0,408.0,63,126.0,173.5,181.0,65.0,29,31.0,23.0,101.5,1.234570e+21
"AYF, AYH",2.0,3.0,80.0,7.0,6.0,18.0,2,1.0,8.0,7.5,3.0,0,3.0,1.0,5.0,2.100000e+01
AYG,25.0,74.0,1371.0,113.0,101.0,296.0,47,112.0,115.0,126.5,46.0,10,28.0,18.0,72.0,1.244000e+03
AYH,31.0,86.0,1940.0,141.0,140.0,353.0,71,110.0,164.0,166.0,64.0,26,44.0,23.0,94.0,1.150000e+03
"AYH, AYO",1.0,3.0,80.0,8.0,2.0,12.0,0,1.0,8.0,8.0,1.0,0,1.0,1.0,2.0,3.000000e+00
AYI,27.0,94.0,2875.0,173.0,129.0,403.0,68,151.0,186.0,186.5,65.0,18,42.0,22.0,109.0,3.150000e+02
"AYI, AYM",1.0,3.0,75.0,1.0,3.0,9.0,0,2.0,8.0,8.0,3.0,0,0.0,1.0,3.0,7.000000e+00
"AYI, AYN",2.0,3.0,120.0,7.0,4.0,13.0,2,3.0,5.0,6.0,3.0,1,3.0,2.0,3.5,9.000000e+00
AYJ,25.0,72.0,1524.0,113.0,102.0,291.0,51,102.0,129.5,130.0,49.0,15,30.0,31.0,77.5,2.850000e+02
AYJ,1.0,3.0,90.0,4.0,6.0,17.0,3,1.0,10.0,9.0,3.0,0,1.0,1.0,6.0,2.600000e+01
AYJ AYT,1.0,3.0,85.0,6.0,2.0,12.0,1,6.0,6.0,6.0,3.0,0,0.0,1.0,5.0,7.000000e+00
"AYJ, AYP",1.0,5.0,85.0,5.0,5.0,15.0,3,4.0,6.0,7.0,2.0,0,1.0,1.0,4.0,7.270000e+02
AYK,35.0,90.0,2085.0,168.5,125.0,377.0,62,78.0,177.5,170.0,64.0,15,35.0,37.0,101.0,2.560000e+02
"AYK, AYQ",1.0,5.0,100.0,5.0,2.0,12.0,0,2.0,8.0,8.0,1.0,0,0.0,0.0,2.0,1.000000e+01
AYL,35.0,107.0,2001.0,163.0,158.0,418.0,75,138.0,191.0,179.5,61.5,19,64.0,30.0,97.5,2.580000e+02
AYM,27.0,72.0,1657.0,134.0,107.0,325.0,54,73.0,144.0,145.0,53.0,18,36.0,34.0,86.0,7.130000e+02
"AYM, AYS",2.0,5.0,80.0,6.0,4.0,15.0,2,10.0,5.0,6.0,3.0,4,3.0,2.0,4.0,5.000000e+00
AYN,23.0,67.0,1374.0,114.0,91.0,284.0,46,56.0,110.0,121.0,36.0,7,34.0,24.0,73.0,2.040000e+02
AYN (71680),2.0,3.0,500.0,5.0,6.0,16.0,3,5.0,9.0,6.0,2.0,0,3.0,0.0,4.5,3.000000e+00
AYO,30.0,89.0,1895.9,163.5,177.0,377.0,61,99.0,164.0,163.5,54.0,13,35.0,33.0,95.5,7.071000e+03
AYP,31.0,93.0,2147.0,162.0,135.0,370.0,61,117.0,170.0,160.0,57.0,10,35.0,29.0,100.5,2.710000e+02
"AYP, AYR",2.0,3.0,100.0,10.0,6.0,18.0,2,9.0,9.0,7.0,2.0,0,1.0,1.0,4.0,2.100000e+01
AYQ,27.0,74.0,1670.0,147.0,176.0,322.0,57,127.0,156.5,151.0,47.5,12,29.0,19.0,80.0,3.480000e+02
AYQ,1.0,5.0,23.0,7.0,5.0,17.0,3,0.0,7.0,9.0,3.0,4,1.0,3.0,4.0,7.000000e+00
AYR,27.0,96.0,1957.0,142.0,124.0,364.0,60,101.0,169.0,164.0,54.0,13,38.0,27.0,86.5,4.550000e+02
AYS,33.0,86.0,1712.0,139.0,109.0,342.0,69,114.0,164.5,152.5,54.0,11,27.0,25.0,90.0,1.237000e+03
AYT,26.0,84.0,1481.0,120.5,115.0,347.0,57,82.0,137.5,137.5,52.0,17,38.0,26.0,72.5,6.801000e+03
BYOD,1.0,3.0,80.0,9.0,5.0,15.0,2,3.0,8.0,7.0,3.0,1,3.0,0.0,4.0,3.000000e+00
CRN,2.0,5.0,88.0,10.0,6.0,18.0,3,3.0,5.0,6.0,3.0,1,2.0,0.0,4.0,8.000000e+00
LBD,15.0,44.0,780.0,70.5,50.0,157.0,25,55.0,78.0,111.0,25.0,5,14.0,15.0,47.0,1.940000e+02
Stat,1.0,3.0,12.0,8.0,7.0,17.0,2,4.0,8.0,8.0,3.0,2,4.0,0.0,1.0,7.000000e+00
Stat107,1.0,3.0,100.0,3.0,5.0,16.0,2,5.0,8.0,8.0,3.0,1,0.0,1.0,2.0,1.000000e+00
lbd,1.0,5.0,87.0,6.0,5.0,14.0,3,2.0,9.0,7.0,2.0,2,1.0,2.0,4.0,1.800000e+01

In [64]:
badsleep_avg_classes = df_badsleep[classes].mean()
badsleep_avg_classes

5.285714285714286

### 🔬 Test Case Checkpoint 🔬

In [65]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for your previous cell.
# - If this cell runs without any errors, you PASSED all test cases!
# - If this cell results in any errors, check your previous cell, make changes, and RE-RUN your code and then this cell.
assert(math.isclose(goodsleep_avg_classes,  5.656)), "The average number of classes for those with good sleep does not appear to have been correctly calculated"
assert(math.isclose(badsleep_avg_classes,  5.285714285714286)), "The average number of classes for those with bad sleep does not appear to have been correctly calculated"

## == SUCCESS MESSAGE ==
# You will only see this message (with the emoji showing) if you passed all test cases:
tada = "\N{PARTY POPPER}"
print(f"{tada} All tests passed! {tada}")

🎉 All tests passed! 🎉

### Analyis: Classes v. Sleeptime

**Q: What is the relationship between classes and average sleep time?  Can you think of a possible *confounding variable* in the observed relationship (or lack thereof) between classes and average sleep time?** Write at least three complete sentences.

Students have average sleep time of 6 hours or higher have an average of more classes. Major can be a confounding variable. Maybe students who have both more courses and more sleep are in easy majors.

<hr style="color: #DD3403;">

# Submission

You're almost done!  All you need to do is to commit your lab to GitHub:

1.  ⚠️ **Make certain to save your work.** ⚠️ To do this, go to **File => Save All**

2.  After you have saved, exit this notebook and follow the Canvas instructions to commit this lab to your Git repository!

3. Your TA will grade your submission and provide you feedback after the lab is due. :)