<h1 style="text-align: center">
<div style="color: #DD3403; font-size: 60%">Data Science DISCOVERY MicroProject #1</div>
<span style="">MicroProject: United States Congress</span>
<div style="font-size: 60%;"><a href="https://discovery.cs.illinois.edu/microproject/01-us-congress/">https://discovery.cs.illinois.edu/microproject/01-us-congress/</a></div>
</h1>

<hr style="color: #DD3403;">

## Introduction

In this microproject, you will use Exploratory Data Analysis (EDA) techniques and the `groupby` function to find various statistics about the current legislators in the United States Congress.  Let's nerd out!

## Dataset: "congress-legislators"

The [@unitedstates project](https://theunitedstates.io/) maintains various high-quality datasets about the United States government.  Specifically, the `congress-legislators` dataset every member "of the United States Congress (1789-Present), congressional committees (1973-Present), committee membership (current only), and presidents and vice presidents of the United States in YAML, JSON, and CSV format."

The URL for the CSV dataset is:
```
https://theunitedstates.io/congress-legislators/legislators-current.csv
```

Load the dataset into a DataFrame called `df`:

In [93]:
import pandas as pd
df = pd.read_csv("https://theunitedstates.io/congress-legislators/legislators-current.csv")
df

,last_name,first_name,middle_name,suffix,nickname,full_name,birthday,gender,type,state,...,opensecrets_id,lis_id,fec_ids,cspan_id,govtrack_id,votesmart_id,ballotpedia_id,washington_post_id,icpsr_id,wikipedia_id
0,Brown,Sherrod,NaN,NaN,NaN,Sherrod Brown,1952-11-09,M,sen,OH,...,N00003535,S307,"H2OH13033,S6OH00163",5051.0,400050,27018.0,Sherrod Brown,NaN,29389.0,Sherrod Brown
1,Cantwell,Maria,NaN,NaN,NaN,Maria Cantwell,1958-10-13,F,sen,WA,...,N00007836,S275,"S8WA00194,H2WA01054",26137.0,300018,27122.0,Maria Cantwell,NaN,39310.0,Maria Cantwell
2,Cardin,Benjamin,L.,NaN,NaN,Benjamin L. Cardin,1943-10-05,M,sen,MD,...,N00001955,S308,"H6MD03177,S6MD03177",4004.0,400064,26888.0,Ben Cardin,NaN,15408.0,Ben Cardin
3,Carper,Thomas,Richard,NaN,NaN,Thomas R. Carper,1947-01-23,M,sen,DE,...,N00012508,S277,S8DE00079,663.0,300019,22421.0,Tom Carper,NaN,15015.0,Tom Carper
4,Casey,Robert,P.,Jr.,Bob,"Robert P. Casey, Jr.",1960-04-13,M,sen,PA,...,N00027503,S309,S6PA00217,47036.0,412246,2541.0,"Bob Casey, Jr.",NaN,40703.0,Bob Casey Jr.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,Flood,Mike,NaN,NaN,NaN,Mike Flood,1975-02-23,M,rep,NE,...,NaN,NaN,H2NE01118,NaN,456868,NaN,Mike Flood,NaN,NaN,Mike Flood (politician)
535,Finstad,Brad,NaN,NaN,NaN,Brad Finstad,1976-05-30,M,rep,MN,...,NaN,NaN,H2MN01223,NaN,456869,NaN,Brad Finstad,NaN,NaN,Brad Finstad
536,Peltola,Mary,Sattler,NaN,NaN,Mary Sattler Peltola,1973-08-31,F,rep,AK,...,NaN,NaN,H2AK01158,NaN,456870,NaN,Mary Peltola,NaN,NaN,Mary Peltola
537,Ryan,Patrick,NaN,NaN,NaN,Patrick Ryan,1982-03-28,M,rep,NY,...,NaN,NaN,H8NY19223,NaN,456871,NaN,Pat Ryan (New York),NaN,NaN,Pat Ryan (politician)
538,Sempolinski,Joseph,NaN,NaN,NaN,Joseph Sempolinski,1982-02-10,M,rep,NY,...,NaN,NaN,H2NY23137,NaN,456872,NaN,Joe Sempolinski,NaN,NaN,Joe Sempolinski

<hr style="color: #DD3403;">

## Puzzle 1: Splitting The House of Representatives and The Senate

In this dataset, each row is one member of Congress.  The United States Congress is bicameral, being made up of both the House of Representatives and the Senate.  In the dataset:

- Representatives in the House of Representatives represent a district, which is encoded in the `district` column.  (Senators will have the `district` column blank.)
- Senators are elected for six years, with one-third of the senators up for election every two years.  The `senate_class` denotes which election class a senator is in.  (Representatives will have the `senate_class` column blank.)

Create two new DataFrames, `df_house` and `df_senate`, that contain members of the House of Representatives and the Senate:

In [94]:
df_house = df[df.district.notnull()]
df_house

,last_name,first_name,middle_name,suffix,nickname,full_name,birthday,gender,type,state,...,opensecrets_id,lis_id,fec_ids,cspan_id,govtrack_id,votesmart_id,ballotpedia_id,washington_post_id,icpsr_id,wikipedia_id
28,Aderholt,Robert,B.,NaN,NaN,Robert B. Aderholt,1965-07-22,M,rep,AL,...,N00003028,NaN,H6AL04098,45516.0,400004,441.0,Robert B. Aderholt,NaN,29701.0,Robert Aderholt
30,Bass,Karen,NaN,NaN,NaN,Karen Bass,1953-10-03,F,rep,CA,...,N00031877,NaN,H0CA33117,62502.0,412404,28963.0,Karen Bass,NaN,21110.0,Karen Bass
32,Bilirakis,Gus,M.,NaN,NaN,Gus M. Bilirakis,1963-02-08,M,rep,FL,...,N00027462,NaN,H6FL09070,1022873.0,412250,17318.0,Gus M. Bilirakis,NaN,20758.0,Gus Bilirakis
33,Bishop,Sanford,D.,Jr.,NaN,"Sanford D. Bishop, Jr.",1947-02-04,M,rep,GA,...,N00002674,NaN,H2GA02031,26194.0,400030,26817.0,Sanford Bishop Jr.,NaN,29339.0,Sanford Bishop
35,Blumenauer,Earl,NaN,NaN,NaN,Earl Blumenauer,1948-08-16,M,rep,OR,...,N00007727,NaN,H6OR03064,43809.0,400033,367.0,Earl Blumenauer,NaN,29588.0,Earl Blumenauer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,Flood,Mike,NaN,NaN,NaN,Mike Flood,1975-02-23,M,rep,NE,...,NaN,NaN,H2NE01118,NaN,456868,NaN,Mike Flood,NaN,NaN,Mike Flood (politician)
535,Finstad,Brad,NaN,NaN,NaN,Brad Finstad,1976-05-30,M,rep,MN,...,NaN,NaN,H2MN01223,NaN,456869,NaN,Brad Finstad,NaN,NaN,Brad Finstad
536,Peltola,Mary,Sattler,NaN,NaN,Mary Sattler Peltola,1973-08-31,F,rep,AK,...,NaN,NaN,H2AK01158,NaN,456870,NaN,Mary Peltola,NaN,NaN,Mary Peltola
537,Ryan,Patrick,NaN,NaN,NaN,Patrick Ryan,1982-03-28,M,rep,NY,...,NaN,NaN,H8NY19223,NaN,456871,NaN,Pat Ryan (New York),NaN,NaN,Pat Ryan (politician)
538,Sempolinski,Joseph,NaN,NaN,NaN,Joseph Sempolinski,1982-02-10,M,rep,NY,...,NaN,NaN,H2NY23137,NaN,456872,NaN,Joe Sempolinski,NaN,NaN,Joe Sempolinski

In [95]:
df_senate = df[df.senate_class.notnull()]
df_senate

,last_name,first_name,middle_name,suffix,nickname,full_name,birthday,gender,type,state,...,opensecrets_id,lis_id,fec_ids,cspan_id,govtrack_id,votesmart_id,ballotpedia_id,washington_post_id,icpsr_id,wikipedia_id
0,Brown,Sherrod,NaN,NaN,NaN,Sherrod Brown,1952-11-09,M,sen,OH,...,N00003535,S307,"H2OH13033,S6OH00163",5051.0,400050,27018.0,Sherrod Brown,NaN,29389.0,Sherrod Brown
1,Cantwell,Maria,NaN,NaN,NaN,Maria Cantwell,1958-10-13,F,sen,WA,...,N00007836,S275,"S8WA00194,H2WA01054",26137.0,300018,27122.0,Maria Cantwell,NaN,39310.0,Maria Cantwell
2,Cardin,Benjamin,L.,NaN,NaN,Benjamin L. Cardin,1943-10-05,M,sen,MD,...,N00001955,S308,"H6MD03177,S6MD03177",4004.0,400064,26888.0,Ben Cardin,NaN,15408.0,Ben Cardin
3,Carper,Thomas,Richard,NaN,NaN,Thomas R. Carper,1947-01-23,M,sen,DE,...,N00012508,S277,S8DE00079,663.0,300019,22421.0,Tom Carper,NaN,15015.0,Tom Carper
4,Casey,Robert,P.,Jr.,Bob,"Robert P. Casey, Jr.",1960-04-13,M,sen,PA,...,N00027503,S309,S6PA00217,47036.0,412246,2541.0,"Bob Casey, Jr.",NaN,40703.0,Bob Casey Jr.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,Hickenlooper,John,Wright,NaN,NaN,John W. Hickenlooper,1952-02-07,M,sen,CO,...,N00044206,S408,S0CO00575,NaN,456797,NaN,John Hickenlooper,NaN,NaN,John Hickenlooper
463,Hagerty,Bill,Francis,NaN,NaN,Bill Hagerty,1959-08-14,M,sen,TN,...,N00045369,S407,S0TN00169,NaN,456798,128466.0,Bill Hagerty,NaN,NaN,Bill Hagerty (politician)
521,Padilla,Alejandro,NaN,NaN,Alex,Alex Padilla,1973-03-22,M,sen,CA,...,N00047888,S413,S2CA00955,NaN,456856,NaN,Alex Padilla,NaN,NaN,Alex Padilla
522,Ossoff,Jon,NaN,NaN,NaN,Jon Ossoff,1987-02-16,M,sen,GA,...,N00040675,S414,"H8GA06195,S8GA00180",NaN,456857,NaN,Jon Ossoff,NaN,NaN,Jon Ossoff
523,Warnock,Raphael,Gamaliel,NaN,NaN,Raphael G. Warnock,1969-07-23,M,sen,GA,...,N00046489,S415,S0GA00559,NaN,456858,NaN,Raphael Warnock,NaN,NaN,Raphael Warnock

<hr style="color: #DD3403;">

## Puzzle 2: Find the Controlling Party of the House of Representatives

In each body of Congress, the "controlling party" is the party that has the majority of the members.  Using `groupby`, create a DataFrame `df_house_party` that counts the number of members in each political party in the House of Representatives:

In [96]:
df_house_sth = df_house.groupby("party").agg("count").reset_index()
df_house_party = df_house_sth[(df_house_sth.party == "Democrat") | (df_house_sth.party == "Republican")]
df_house_party

,party,last_name,first_name,middle_name,suffix,nickname,full_name,birthday,gender,type,...,opensecrets_id,lis_id,fec_ids,cspan_id,govtrack_id,votesmart_id,ballotpedia_id,washington_post_id,icpsr_id,wikipedia_id
0,Democrat,225,225,106,9,12,225,225,225,225,...,221,0,225,157,225,202,206,0,200,225
1,Republican,214,214,93,6,13,214,214,214,214,...,208,0,214,129,214,170,185,0,159,213

### Puzzle 2 Analysis: How many Democrats and Republicans in the House?

Using the result above, fill out the following cell with the number of Democrats and Republications:

In [97]:
democrats_in_house = 225
republications_in_house = 214

<hr style="color: #DD3403;">

## Puzzle 3: Find the Youngest Member of each Party in the House of Representatives

In the House of Representatives, who is the youngest member Democrat and who is the youngest Republican?

In [98]:
# ...feel free to add additional Python "Code Cells" if you need to!
d = df_house[df_house.party == "Republican"]
df_house_demo_birth = d.sort_values("birthday",ascending = False)
df_house_demo_birth

,last_name,first_name,middle_name,suffix,nickname,full_name,birthday,gender,type,state,...,opensecrets_id,lis_id,fec_ids,cspan_id,govtrack_id,votesmart_id,ballotpedia_id,washington_post_id,icpsr_id,wikipedia_id
498,Cawthorn,Madison,NaN,NaN,NaN,Madison Cawthorn,1995-08-01,M,rep,NC,...,N00046252,NaN,H0NC11233,NaN,456833,NaN,Madison Cawthorn,NaN,NaN,Madison Cawthorn
489,LaTurner,Jacob,NaN,NaN,Jake,Jake LaTurner,1988-02-17,M,rep,KS,...,N00044232,NaN,H0KS02188,NaN,456824,NaN,NaN,NaN,NaN,Jake LaTurner
471,Cammack,Katherine,NaN,NaN,Kat,Kat Cammack,1988-02-16,F,rep,FL,...,N00045978,NaN,H0FL03175,NaN,456806,NaN,NaN,NaN,NaN,Kat Cammack
491,Meijer,Peter,James,NaN,NaN,Peter Meijer,1988-01-10,M,rep,MI,...,N00044884,NaN,H0MI03308,NaN,456826,NaN,NaN,NaN,NaN,Peter Meijer
470,Boebert,Lauren,Opal,NaN,NaN,Lauren Boebert,1986-12-15,F,rep,CO,...,N00045974,NaN,H0CO03165,NaN,456805,NaN,Lauren Boebert,NaN,NaN,Lauren Boebert
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,Baird,James,R.,NaN,NaN,James R. Baird,1945-06-04,M,rep,IN,...,N00041954,NaN,H8IN04199,NaN,412777,86013.0,James Baird,NaN,21903.0,Jim Baird (politician)
79,Foxx,Virginia,NaN,NaN,NaN,Virginia Foxx,1943-06-29,F,rep,NC,...,N00026166,NaN,H4NC05146,1013052.0,400643,6051.0,Virginia Foxx,NaN,20521.0,Virginia Foxx
84,Granger,Kay,NaN,NaN,NaN,Kay Granger,1943-01-18,F,rep,TX,...,N00008799,NaN,H6TX12060,45709.0,400157,334.0,Kay Granger,NaN,29762.0,Kay Granger
49,Carter,John,R.,NaN,NaN,John R. Carter,1941-11-06,M,rep,TX,...,N00025095,NaN,H2TX31044,1004257.0,400068,49296.0,John Carter,NaN,20356.0,John Carter (Texas politician)
161,Rogers,Harold,NaN,NaN,Hal,Harold Rogers,1937-12-31,M,rep,KY,...,N00003473,NaN,H0KY05015,6739.0,400340,26875.0,Harold Rogers,NaN,14854.0,Hal Rogers

### Puzzle 3 Analysis: How many Democrats and Republicans in the House?

Using the result above, provide the **full name** of the youngest Democrat and Republican:

In [99]:
youngest_democrat_in_house = "Alexandria Ocasio-Cortez"
youngest_republican_in_house = "Madison Cawthorn"

<hr style="color: #DD3403;">

## 🔬 Microproject Checkpoint Tests 🔬

In [103]:
## == CHECKPOINT TEST CASES ==
# - This read-only cell contains test cases for the microproject.
# - If this cell runs without any error in the output, you PASSED all test cases!
# - If this cell results in any errors, check you previous cells, make changes, and RE-RUN your code and then this cell.

tada = "\N{PARTY POPPER}"
R = -1
D = R - 1

assert( len(df) > 500 )
assert( len(df_senate) <= 100 )
assert( len(df_house) == len(df) - len(df_senate) )

print(f"{tada} Puzzle 1: All Tests Passed! {tada}")

assert(len(df_house_party) == 2)
assert((df_house_party.index[0] == "Democrat" or df_house_party.index[0] == "Republican" or "party" in df.columns.tolist()))
assert(len(df) - len(df_senate) - df_house.value_counts(df.columns.tolist()[12])[df.sort_values(df.columns.tolist()[6]).iloc[R][df.columns.tolist()[12]]] == democrats_in_house)
assert(len(df) - len(df_senate) - df_house.value_counts(df.columns.tolist()[12])[df.sort_values(df.columns.tolist()[6]).iloc[D][df.columns.tolist()[12]]] == republications_in_house)
print(f"{tada} Puzzle 2: All Tests Passed! {tada}")

assert(df.sort_values(df.columns.tolist()[6]).iloc[D][df.columns.tolist()[5]] == youngest_democrat_in_house)
assert(df.sort_values(df.columns.tolist()[6]).iloc[R][df.columns.tolist()[5]] == youngest_republican_in_house)
print(f"{tada} Puzzle 3: All Tests Passed! {tada}")

print(f"{tada}{tada} All Tests Passed! {tada}{tada}")

🎉 Puzzle 1: All Tests Passed! 🎉
🎉 Puzzle 2: All Tests Passed! 🎉
🎉 Puzzle 3: All Tests Passed! 🎉
🎉🎉 All Tests Passed! 🎉🎉

<hr style="color: #DD3403;">

## Submission

You're almost done!  All you need to do is to commit your lab to GitHub and run the GitHub Actions Grader:

1.  ⚠️ **Make certain to save your work.** ⚠️ To do this, go to **File => Save All**

2.  After you have saved, exit this notebook and follow the instructions to commit and grade this MicroProject!